# Generated by Django 3.0.8 on 2020-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='song',
        ),
        migrations.AddField(
            model_name='day',
            name='song',
            field=models.ManyToManyField(default=None, null=True, to='challange.Song'),
        ),
    ]
