# Generated by Django 3.0.8 on 2020-08-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0005_auto_20200728_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challange.Day', verbose_name='Dzień'),
            preserve_default=False,
        ),
    ]
