# Generated by Django 3.0.8 on 2020-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0007_auto_20200803_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='condition',
            field=models.CharField(default='wybierz', max_length=128, verbose_name='Warunek'),
        ),
    ]
