# Generated by Django 3.0.8 on 2020-07-28 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Imie i nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł')),
                ('artist', models.CharField(max_length=128, verbose_name='Autor')),
                ('link', models.URLField(blank=True, db_index=True, unique=True, verbose_name='Link do YT')),
                ('person', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='challange.Person', verbose_name='Kto zaproponowal')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('condition', models.CharField(default='wybierz', max_length=64, verbose_name='Warunek')),
                ('event', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='challange.Event', verbose_name='Która edycja')),
                ('song', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='challange.Song')),
            ],
        ),
    ]
