# Generated by Django 3.0.8 on 2020-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111, verbose_name='Imie i nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=111, verbose_name='Tytuł')),
                ('artist', models.CharField(max_length=111, verbose_name='Autor')),
                ('link', models.URLField(blank=True, db_index=True, unique=True, verbose_name='Link do YT')),
                ('person', models.ManyToManyField(to='challange.Person', verbose_name='Kto zaproponowal')),
            ],
        ),
    ]
