# Generated by Django 3.0.8 on 2020-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='edition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Piosenka na literę...'), (2, 'Artysta na literę...')], default='1', verbose_name='Która edycja'),
        ),
    ]
