# Generated by Django 3.0.8 on 2020-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0002_auto_20200716_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='edition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Piosenka na literę...'), (2, 'Artysta na literę...')], default='1', verbose_name='Która edycja'),
        ),
    ]
