# Generated by Django 3.0.8 on 2020-07-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0003_auto_20200716_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='edition',
        ),
        migrations.AddField(
            model_name='day',
            name='condition',
            field=models.CharField(default='wybierz', max_length=64, verbose_name='Warunek'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Imie i nazwisko'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=128, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Tytuł'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=128)),
                ('eventday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challange.Day')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='event',
            field=models.ManyToManyField(default='wybierz', to='challange.Event', verbose_name='Która edycja'),
        ),
    ]
