# Generated by Django 3.0.8 on 2020-07-16 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0004_auto_20200716_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
